---
output:
 bookdown::word_document2:
   reference_docx: "vcr-fish-template.docx"
title: "Improving estimates of eelgrass meadow density and carbon sequestration with soap film smoothers"
author:
  - Sean Hardison, University of Virginia
  - Max Castorani, University of Virginia
bibliography: soap_film_bib.bib
csl: ecology.csl
---

## Abstract {-}

## Introduction {-}

The carbon sequestration potential of seagrass meadows per unit area rivals that of terrestrial forests, and in the absence of habitat degradation, some seagrass meadows (e.g., *Posidonia* spp.) may retain sequestered carbon for millenia [@lo2008; @fourqurean2012]. These carbon storage attributes and the capacity of meadows to be restored through management actions that align with broader ecosystem management objectives (e.g., shoreline protection, conserving fish habitat) have resulted in seagrasses being considered as a prime candidate for Blue Carbon climate remediation strategies [@duarte2013; @lovelock2019]. A popular approach for implementing Blue Carbon strategies is known as Payments for Ecosystem Services (PES), which involve buyers (oftentimes representing polluting corporations) paying stewards to conserve or restore ecosystems that sequester carbon [@shilland2021]. Through adherence to certain regulations put forth by non-governmental agencies like the Voluntary Carbon Standard (VCS), seagrass restoration and conservation projects may use this mechanism to convert the carbon capture benefits of seagrasses into carbon credits with monetary value [@emmer2015; @needelman2018; @oreska2020]. However, despite the extensive literature documenting seagrasses as significant carbon sinks [e.g., @lo2008; @oreska2017; @oreska2020], their inclusion in PES services is still nascent due to technical and policy-based challenges [@shilland2021]. 

In order for seagrass restoration or conservation projects to become eligible to engage in PES under the VCS guidelines, greenhouse gas (GHG) fluxes (e.g., $\textrm{CO}_2$, $\textrm{CH}_4$, $\textrm{N}_2\textrm{O}$) must be estimated under both baseline and project scenarios [@needelman2018]. The purpose of the baseline scenario is to estimate the GHG fluxes that would have occurred in the absence of the project, and the project scenario to measure GHG fluxes and sediment carbon pools as the project unfolds over time [@oreska2018]. This method allows for calculating the enhanced carbon sequestration due to seagrass, the balance of GHG fluxes relative to a baseline, and the turnover of carbon in meadow sediments [@oreska2020]. The VCS methodology ensures that credit is given to those projects that document drawdown of GHGs relative to a baseline [@oreska2018]. 

Given potential logistical constraints involved in surveying GHG fluxes and sediment carbon pools *in situ*, projects may qualify for carbon credits by using carbon sequestration and GHG flux rates put forth in the literature and accepted by VCS [@oreska2018; @needelman2018]. However, the highest quality data for generating the relevant emissions metrics, known as "Tier 3" data, are those collected *in situ* within the project boundaries [@emmer2015]. When the meadow boundary is also known, it becomes feasible to generate spatially-referenced estimates of sequestered carbon across the meadow as well as more precise estimates of aggregate GHG fluxes [@oreska2017; @oreska2020]. The spatial perspective afforded by such data, while not strictly required for accreditation, provides managers with insights into where further restoration or natural expansion is likely to be successful [@oreska2021]. Given the potential societal benefits attributable to these data and the difficulty inherent in their collection, the choice of statistical method for estimating GHG fluxes and sequestered carbon across the meadow needs to be highly effective under sample size limitations.

The most commonly used statistical methods to estimate the spatial distribution of sequestered carbon and GHG fluxes involve kriging [@oreska2017; @meng2019; @oreska2020], a technique that emerged out of the mining industry to predict spatial variables at unmeasured locations [@krige1951]. In the context of a seagrass meadow, the total $\textrm{C}_\textrm{org}$ stock may be estimated simply by multiplying the predicted areal density of $\textrm{C}_\textrm{org}$, given by kriging, with total meadow area [@oreska2017]. Kriging methods may be extended to predict multiple responses, such as with cokriging [@bivand2013], or with multiple predictors through their interpretation as generalized additive models (GAMs) with Gaussian process regression smoothers [@kammann2003; @wood2017]. 

However, where kriging falls short is when smooths are desired around complex spatial domains with biologically meaningful boundaries. For example, consider the U-shaped spatial domain presented in Figure 1, also known as Ramsay's test function [@ramsay2002; @simpson2016]. Imagine that a seagrass meadow exists within this domain and has grown around a landform resulting in the meadow's U shape. A kriged surface of the region would suggest that the prongs of the U were more similar to each other than the prongs were to the "base" of the U shape. While the kriging model is performing as expected, this conclusion is clearly not biologically tenable. Kriging with covariates, like distance to the boundary, is one way to solve this problem. However, such methods will still provide non-sensical predictions outside of the boundary and can quickly reduce model parsimony.

While usually not as dramatic as Ramsay's test functon, seagrass meadows frequently occur in spatially complex domains. Meadows emerge around peninsulas and islands [@traganos2018; @ha2020], and also form clonal structures extending outwards into patches of suitable habitat [@nahirnick2019]. These spatial complexities may be addressed through a special class of smoothers called soap film smoothers [@wood2008; @wood2017]. Soap film smoothers solve the problem of smoothing across boundaries by compartmentalizing smooths to within pre-specified areas, for example, the extent of a seagrass meadow identified via remote sensing. Further, the interpolated surface provided by a soap film smoother, like the density of shoots in a *Zostera marina* eelgrass meadow [@oreska2017], tends to decline towards the boundary. As such, the attributes of the soap film smoother are uniquely analogous to those of a seagrass meadow at a landscape scale, greatly enhancing the utility of the model.

In this work, we compare the utility of Gaussian process regression (kriging) with and without covariates to that of soap film smoothers, with a focus on estimating total sequestered $\textrm{C}_\textrm{org}$ in *Z. marina* eelgrass meadows. Our work shows that soap film models can provide estimates of seagrass meadow $\textrm{C}_\textrm{org}$ that have lower predictive error and fit better than classical kriging methods by capturing the tendency of meadow attributes to decline towards the meadow boundary. The soap film approach will benefit the adoption of seagrass meadows into PES strategies in data poor ecosystems by reducing prediction errors without requiring spatially comprehensive covariates like depth within the meadow domain. 


## Methods {-}



## Results {-}

## Discussion {-}